UPDATE

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -108,8 +108,6 @@ jobs:
       test_site_repo_config_branch: "${{ github.job }}-config-only"
       test_site_repo_pr_branch: "${{ github.job }}-automatic-config-export"
       test_site_repo_pr_branch_base: "${{ github.job }}-staging"
-#    needs: [test-1]
-#    if: ${{ always() }}
     steps:
 
       - uses: actions/checkout@v4
@@ -133,6 +131,7 @@ jobs:
       - name: 'Test setup for testing creating a PR'
         working-directory: test
         run: |
+          set -eu
           cd site
           git remote add remote-config ../remote
           git fetch remote-config
@@ -175,7 +174,7 @@ jobs:
           git -C remote fetch origin ${{ env.test_config_repo_branch }}
           
           if [[ "$(git -C remote rev-parse origin/${{ env.test_config_repo_branch }})" != "$(git -C site rev-parse origin/${{ env.test_site_repo_config_branch }})" ]]; then
-            echo "TEST FAILURE: The Drupal site repo's config-only branch wasn't in sync with the config repo's main branch." >> "$GITHUB_STEP_SUMMARY"
+            echo "**TEST FAILURE:** The Drupal site repo's config-only branch wasn't in sync with the config repo's main branch." >> "$GITHUB_STEP_SUMMARY"
             exit=1
           fi
           
@@ -183,7 +182,7 @@ jobs:
           git fetch
           git checkout ${{ env.test_site_repo_pr_branch_base }}
           if [[ "$(gh pr list -H ${{ env.test_site_repo_pr_branch }} --json id)" == "[]" ]]; then
-            echo "TEST FAILURE: There should be a PR created." >> "$GITHUB_STEP_SUMMARY"
+            echo "**TEST FAILURE:** There should be a PR created." >> "$GITHUB_STEP_SUMMARY"
             exit=1
           fi
           
@@ -194,13 +193,106 @@ jobs:
         with:
           branch_prefix: "${{ github.job }}-"
 
-#      - name: Test-specific tear-down
-#        if: ${{ always() }}
-#        env:
-#          GH_TOKEN: ${{ secrets.TEST_SITE_REPO_TOKEN }}
-#        working-directory: test/site
-#        run: |
-#          # Test-specific tear-down
-#          if [[ "$(gh pr list -H ${{ env.test_site_repo_pr_branch }} --json id)" != "[]" ]]; then
-#            gh pr close ${{ env.test_site_repo_pr_branch }}
-#          fi
+  test:
+    name: Test updating an existing PR.
+    runs-on: ubuntu-latest
+    env:
+      test_config_repo_branch: "${{ github.job }}-main"
+      test_site_repo_config_branch: "${{ github.job }}-config-only"
+      test_site_repo_pr_branch: "${{ github.job }}-automatic-config-export"
+      test_site_repo_pr_branch_base: "${{ github.job }}-staging"
+    steps:
+
+      - uses: actions/checkout@v4
+        with:
+          path: test/update-config
+
+      - uses: ./test/update-config/.github/actions/test-setup
+        with:
+          branch_prefix: "${{ github.job }}-"
+          test_config_repo: ${{ vars.TEST_CONFIG_REPO }}
+          test_config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
+          test_config_repo_branch: ${{ env.test_config_repo_branch }}
+          test_site_repo: ${{ vars.TEST_SITE_REPO }}
+          test_site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+          test_site_repo_config_branch: ${{ env.test_site_repo_config_branch }}
+          test_site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
+          test_site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
+
+      # TODO FACTOR OUT COMMON ASSERTIONS, POST TEST NORMALIZATION AND TEAR DOWN.
+
+      - name: 'Test setup for testing updating an existing PR'
+        working-directory: test
+  # TODO: See if I'm only using git config.name etc. as few times as pos
+        run: |
+          set -eu
+          cd site
+          # Ensure the site repo config branch is behind the config repo.
+          git remote add remote-config ../remote
+          git fetch remote-config
+          git checkout -b ${{ env.test_site_repo_config_branch }} remote-config/${{ env.test_config_repo_branch }}^
+          tmp_dir=$(mktemp -d)
+          cp * "$tmp_dir"
+          git push origin HEAD
+          
+          # Set up an existing PR.
+          git checkout ${{ env.test_site_repo_pr_branch_base }}
+          git rm config/sync/*
+          git commit --amend -m "Initial commmit"
+          git push origin HEAD --force
+          
+          git checkout -b ${{ env.test_site_repo_pr_branch }}
+          cp -r "$tmp_dir"/* config/sync
+          git add config/sync
+          git commit -m "Update"
+          git push origin HEAD
+          
+          gh pr create --head ${{ env.test_site_repo_pr_branch }} --base ${{ env.test_site_repo_pr_branch_base }}
+          
+          rm -rf "$tmp_dir"
+
+      - uses: ./test/update-config
+        with:
+          config_repo: ${{ vars.TEST_CONFIG_REPO }}
+          config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
+          config_repo_branch: ${{ env.test_config_repo_branch }}
+          site_repo: ${{ vars.TEST_SITE_REPO }}
+          site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+          site_repo_config_branch: ${{ env.test_site_repo_config_branch }}
+          site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
+          site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
+
+      - name: Assert the state after running the action
+        env:
+          GH_TOKEN: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+        working-directory: test
+        run: |
+          # Assert the state after running the action
+          set -eux
+          exit=0
+          cat "$GITHUB_STEP_SUMMARY"
+          
+          git -C site fetch origin ${{ env.test_site_repo_config_branch }}
+          git -C remote fetch origin ${{ env.test_config_repo_branch }}
+          
+          if [[ "$(git -C remote rev-parse origin/${{ env.test_config_repo_branch }})" != "$(git -C site rev-parse origin/${{ env.test_site_repo_config_branch }})" ]]; then
+            echo "**TEST FAILURE:** The Drupal site repo's config-only branch wasn't in sync with the config repo's main branch." >> "$GITHUB_STEP_SUMMARY"
+            exit=1
+          fi
+          
+          cd site
+          git fetch
+          git checkout ${{ env.test_site_repo_pr_branch_base }}
+          if [[ "$(gh pr list -H ${{ env.test_site_repo_pr_branch }} --json id)" == "[]" ]]; then
+            echo "**TEST FAILURE:** There should still be an existing PR." >> "$GITHUB_STEP_SUMMARY"
+            exit=1
+          fi
+          
+          exit $exit
+
+      - uses: ./test/update-config/.github/actions/test-teardown
+        if: ${{ always() }}
+        with:
+          branch_prefix: "${{ github.job }}-"
+
+# TODO: TEST UPDATE'S PRESENT BUT MAKE NO DIFFERENCE
