UPDATE

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -123,8 +123,6 @@ jobs:
           test_site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
           test_site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
 
-      # TODO FACTOR OUT COMMON ASSERTIONS, POST TEST NORMALIZATION AND TEAR DOWN.
-
       - name: 'Test setup for testing creating a PR'
         working-directory: test
         run: |
@@ -226,8 +224,6 @@ jobs:
           test_site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
           test_site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
 
-      # TODO FACTOR OUT COMMON ASSERTIONS, POST TEST NORMALIZATION AND TEAR DOWN.
-
       - name: 'Test setup for testing updating an existing PR'
         env:
           GH_TOKEN: ${{ secrets.TEST_SITE_REPO_TOKEN }}
@@ -300,4 +296,96 @@ jobs:
         with:
           branch_prefix: "${{ github.job }}-"
 
-# TODO: TEST UPDATE'S PRESENT BUT MAKE NO DIFFERENCE
+  test-identical-config:
+    #    if: false
+    name: Test updating the mirrored config branch only to find it matches what's already in staging.
+    runs-on: ubuntu-latest
+    env:
+      test_config_repo_branch: "${{ github.job }}-main"
+      test_site_repo_config_branch: "${{ github.job }}-config-only"
+      test_site_repo_pr_branch: "${{ github.job }}-automatic-config-export"
+      test_site_repo_pr_branch_base: "${{ github.job }}-staging"
+    steps:
+
+      - uses: actions/checkout@v4
+        with:
+          path: test/update-config
+
+      - uses: ./test/update-config/.github/actions/test-setup
+        with:
+          branch_prefix: "${{ github.job }}-"
+          test_config_repo: ${{ vars.TEST_CONFIG_REPO }}
+          test_config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
+          test_config_repo_branch: ${{ env.test_config_repo_branch }}
+          test_site_repo: ${{ vars.TEST_SITE_REPO }}
+          test_site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+          test_site_repo_config_branch: ${{ env.test_site_repo_config_branch }}
+          test_site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
+          test_site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
+
+
+      - name: 'Test setup for testing matching config'
+        working-directory: test
+        run: |
+          set -eux
+          cd site
+          git remote add remote-config ../remote
+          git fetch remote-config
+          git checkout -b ${{ env.test_site_repo_config_branch }} remote-config/${{ env.test_config_repo_branch }}^
+          tmp_dir=$(mktemp -d)
+          cp * "$tmp_dir"
+          git push origin HEAD
+
+      - uses: ./test/update-config
+        with:
+          config_repo: ${{ vars.TEST_CONFIG_REPO }}
+          config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
+          config_repo_branch: ${{ env.test_config_repo_branch }}
+          site_repo: ${{ vars.TEST_SITE_REPO }}
+          site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+          site_repo_config_branch: ${{ env.test_site_repo_config_branch }}
+          site_repo_pr_branch: ${{ env.test_site_repo_pr_branch }}
+          site_repo_pr_branch_base: ${{ env.test_site_repo_pr_branch_base }}
+
+      - uses: ./test/update-config/.github/actions/test-assertions
+        with:
+          test_config_repo: ${{ vars.TEST_CONFIG_REPO }}
+          test_config_repo_branch: ${{ env.test_config_repo_branch }}
+          test_config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
+          test_site_repo: ${{ vars.TEST_SITE_REPO }}
+          test_site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+          test_site_repo_config_branch: ${{ env.test_site_repo_config_branch }}
+
+      - name: Assert the state after running the action
+        env:
+          GH_TOKEN: ${{ secrets.TEST_SITE_REPO_TOKEN }}
+        working-directory: test/site
+        run: |
+          set -eu
+          exit=0
+          tmp_dir=$(mktemp -d)
+          git checkout ${{ env.test_site_repo_config_branch }}
+          cp * "$tmp_dir"
+          
+          git checkout ${{ env.test_site_repo_pr_branch }}
+          if [[ "$(gh pr list --json id)" != "[]" ]]; then
+            echo "**TEST FAILURE:** There should not be a PR created." >> "$GITHUB_STEP_SUMMARY"
+            exit=1
+          fi
+          
+          git checkout ${{ env.test_site_repo_pr_branch_base }}
+          rm config/sync/*
+          mv "$tmp_dir"/* config/sync
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "**TEST FAILURE:** The site staging branch should match the config repo branch." >> "$GITHUB_STEP_SUMMARY"
+            exit=1          
+          fi
+          
+          rm -rf "$tmp_dir"
+          
+          exit $exit
+
+      - uses: ./test/update-config/.github/actions/test-teardown
+        if: ${{ always() }}
+        with:
+          branch_prefix: "${{ github.job }}-"
